project_token: e3b1f8d9e6cc5a68442ba7fe
name: text-classifier
jobs: 
  - job_id: b8a4b177-4395-4e2b-802b-20af9fe46fc7
    language: python
    name: train-text-classifier-model 
    entrypoint: "train-text-classifier-model.py"
  - job_id: a3ff4cd9-ab49-4efb-8340-4c00519b120c
    language: python
    name: classify-text
    entrypoint: "python classify-text.py --text 'Inside the park?  Pass the peanuts.  He throws a mean heater. I love Wade Boggs.'"
    dependencies: ["b8a4b177-4395-4e2b-802b-20af9fe46fc7"]

